spring:
    config:
        activate:
            on-profile: local
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://127.0.0.1:5432/HDSBD
        username: DSB_APP
        password: pp8Ow2s2MdEdRm6VSaQDyQ== 
    jpa:
        show-sql: true
        format_sql: true
        use_sql_comments: true
        hibernate:
            ddl-auto: none
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                jdbc:
                    timezone: Asia/Seoul
        
logging:
    level:
        biz: DEBUG
        root: INFO
    file:
        path: D:/00.dashboard/log
        name: HDSBD
lotus:
    token_exp_sec: 7200 #1800