spring:
    application:
        name: HOMEDASHBOARD
    #profiles:
        #active: ${SPRING_PROFILES_ACTIVE}
    messages:
      basename: message/message
      encoding: UTF-8
      fallback-to-system-locale: false #locale 파일 못찾았을 때 기본 locale 사용여부
      use-code-as-default-message: false #default 못찾았을 때 Exception 여부
      always-use-message-format: false #전달받은 인자를 제외하고 메세지를 읽어들이는 MessageFormat 규칙을 항상 적용할 것인지에 대한 여부
    jpa:
        hibernate:
            ddl-auto: none
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                jdbc:
                    timezone: Asia/Seoul
server:
  error:
    include-stacktrace: never